#!/usr/bin/env python3
"""
Streamlit Web Interface for Golf Data Analyzer
Run with: streamlit run golf_analyzer_web.py
"""

import streamlit as st
import json
import pandas as pd
from collections import defaultdict
import plotly.express as px
import plotly.graph_objects as go

# Page config
st.set_page_config(
    page_title="Golf Performance Analyzer",
    page_icon="⛳",
    layout="wide"
)

@st.cache_data
def load_data(file_path='golfshot_scores.json'):
    """Load golf data from JSON file"""
    try:
        with open(file_path, 'r') as f:
            return json.load(f)
    except FileNotFoundError:
        return None

def load_data_from_upload(uploaded_file):
    """Load data from uploaded file"""
    try:
        data = json.load(uploaded_file)
        return data
    except Exception as e:
        st.error(f"Error loading file: {e}")
        return None

def get_courses(rounds):
    """Get list of unique courses"""
    courses = set()
    for r in rounds:
        if r.get('course'):
            courses.add(r['course'])
    return sorted(list(courses))

def analyze_course(rounds, course_name):
    """Analyze performance at a specific course"""
    course_rounds = [r for r in rounds if r.get('course') == course_name]
    
    if not course_rounds:
        return None
    
    # Calculate stats
    stats = {
        'total_rounds': len(course_rounds),
        'scores': [r['total_score'] for r in course_rounds if r.get('total_score')],
        'dates': [r.get('date', 'Unknown') for r in course_rounds],
    }
    
    if stats['scores']:
        stats['avg_score'] = sum(stats['scores']) / len(stats['scores'])
        stats['best_score'] = min(stats['scores'])
        stats['worst_score'] = max(stats['scores'])
    
    # Aggregate hole statistics
    holes_data = defaultdict(lambda: {
        'scores': [], 'pars': [], 'eagles': 0, 'birdies': 0,
        'pars_count': 0, 'bogeys': 0, 'double_bogeys': 0, 'worse': 0
    })
    
    total_stats = defaultdict(int)
    
    for round_data in course_rounds:
        round_stats = round_data.get('stats', {})
        for key, value in round_stats.items():
            total_stats[key] += value
            
        for hole in round_data.get('holes', []):
            hole_num = hole['hole']
            score = hole['score']
            par = hole['par']
            
            holes_data[hole_num]['scores'].append(score)
            holes_data[hole_num]['pars'].append(par)
            
            diff = score - par
            if diff <= -2:
                holes_data[hole_num]['eagles'] += 1
            elif diff == -1:
                holes_data[hole_num]['birdies'] += 1
            elif diff == 0:
                holes_data[hole_num]['pars_count'] += 1
            elif diff == 1:
                holes_data[hole_num]['bogeys'] += 1
            elif diff == 2:
                holes_data[hole_num]['double_bogeys'] += 1
            else:
                holes_data[hole_num]['worse'] += 1
    
    stats['total_stats'] = dict(total_stats)
    stats['holes_data'] = dict(holes_data)
    
    return stats

def analyze_hole(rounds, course_name, hole_num):
    """Analyze a specific hole"""
    course_rounds = [r for r in rounds if r.get('course') == course_name]
    
    hole_data = {
        'scores': [], 'par': None, 'dates': [],
        'eagles': 0, 'birdies': 0, 'pars': 0,
        'bogeys': 0, 'double_bogeys': 0, 'worse': 0
    }
    
    for round_data in course_rounds:
        for hole in round_data.get('holes', []):
            if hole['hole'] == hole_num:
                score = hole['score']
                par = hole['par']
                
                hole_data['scores'].append(score)
                hole_data['par'] = par
                hole_data['dates'].append(round_data.get('date', 'Unknown'))
                
                diff = score - par
                if diff <= -2:
                    hole_data['eagles'] += 1
                elif diff == -1:
                    hole_data['birdies'] += 1
                elif diff == 0:
                    hole_data['pars'] += 1
                elif diff == 1:
                    hole_data['bogeys'] += 1
                elif diff == 2:
                    hole_data['double_bogeys'] += 1
                else:
                    hole_data['worse'] += 1
                break
    
    return hole_data

# Main app
st.title("⛳ Golf Performance Analyzer")
st.markdown("---")

# Sidebar file uploader
st.sidebar.title("📂 Data Source")
uploaded_file = st.sidebar.file_uploader(
    "Upload your golfshot_scores.json file",
    type=['json'],
    help="Upload the JSON file generated by the scraper"
)

# Load data
rounds = None

if uploaded_file is not None:
    rounds = load_data_from_upload(uploaded_file)
    if rounds:
        st.sidebar.success(f"✅ Loaded {len(rounds)} rounds from uploaded file")
else:
    # Try to load from local file
    rounds = load_data()
    if rounds:
        st.sidebar.info(f"✅ Loaded {len(rounds)} rounds from local file")

if rounds is None:
    st.error("❌ No data found!")
    st.info("""
    **To use this app, you need golf data:**
    
    1. **Run the scraper locally:**
       ```
       python3 golfshot_scraper.py
       ```
    
    2. **Upload the generated `golfshot_scores.json` file using the sidebar**
    
    Or place the file in the same directory as this app.
    """)
    st.stop()

st.sidebar.markdown("---")

# Sidebar navigation
st.sidebar.title("Navigation")
page = st.sidebar.radio(
    "Choose Analysis",
    ["📊 Overview", "🏌️ Course Analysis", "🎯 Hole Analysis", "📈 Trends"]
)

# Overview Page
if page == "📊 Overview":
    st.header("Overview")
    
    col1, col2, col3 = st.columns(3)
    
    # Total rounds
    with col1:
        st.metric("Total Rounds", len(rounds))
    
    # Total courses
    courses = get_courses(rounds)
    with col2:
        st.metric("Courses Played", len(courses))
    
    # Total birdies
    total_birdies = sum(r.get('stats', {}).get('birdies', 0) for r in rounds)
    with col3:
        st.metric("Total Birdies", total_birdies)
    
    st.markdown("---")
    
    # Courses by rounds played
    st.subheader("Courses by Rounds Played")
    course_counts = defaultdict(int)
    course_scores = defaultdict(list)
    
    for r in rounds:
        course = r.get('course')
        if course:
            course_counts[course] += 1
            if r.get('total_score'):
                course_scores[course].append(r['total_score'])
    
    courses_df = pd.DataFrame([
        {
            'Course': course,
            'Rounds': count,
            'Avg Score': f"{sum(course_scores[course])/len(course_scores[course]):.1f}" if course_scores[course] else "N/A"
        }
        for course, count in sorted(course_counts.items(), key=lambda x: x[1], reverse=True)
    ])
    
    st.dataframe(courses_df, use_container_width=True)
    
    # Courses by birdies
    st.subheader("Courses by Total Birdies")
    course_birdies = defaultdict(int)
    for r in rounds:
        course = r.get('course')
        if course:
            course_birdies[course] += r.get('stats', {}).get('birdies', 0)
    
    birdies_df = pd.DataFrame([
        {'Course': course, 'Total Birdies': birdies}
        for course, birdies in sorted(course_birdies.items(), key=lambda x: x[1], reverse=True)
    ])
    
    fig = px.bar(birdies_df.head(10), x='Course', y='Total Birdies',
                 title='Top 10 Courses by Birdies')
    st.plotly_chart(fig, use_container_width=True)

# Course Analysis Page
elif page == "🏌️ Course Analysis":
    st.header("Course Analysis")
    
    courses = get_courses(rounds)
    selected_course = st.selectbox("Select a course", courses)
    
    if selected_course:
        stats = analyze_course(rounds, selected_course)
        
        if stats:
            # Summary metrics
            col1, col2, col3, col4 = st.columns(4)
            
            with col1:
                st.metric("Rounds Played", stats['total_rounds'])
            with col2:
                st.metric("Average Score", f"{stats['avg_score']:.1f}" if 'avg_score' in stats else "N/A")
            with col3:
                st.metric("Best Score", stats.get('best_score', 'N/A'))
            with col4:
                st.metric("Worst Score", stats.get('worst_score', 'N/A'))
            
            st.markdown("---")
            
            # Overall statistics
            st.subheader("Overall Statistics")
            col1, col2, col3, col4, col5, col6 = st.columns(6)
            
            total_stats = stats['total_stats']
            with col1:
                st.metric("Eagles", total_stats.get('eagles', 0))
            with col2:
                st.metric("Birdies", total_stats.get('birdies', 0))
            with col3:
                st.metric("Pars", total_stats.get('pars', 0))
            with col4:
                st.metric("Bogeys", total_stats.get('bogeys', 0))
            with col5:
                st.metric("Double Bogeys", total_stats.get('double_bogeys', 0))
            with col6:
                st.metric("Triple+", total_stats.get('worse', 0))
            
            st.markdown("---")
            
            # Score trend
            if len(stats['scores']) > 1:
                st.subheader("Score Trend")
                trend_df = pd.DataFrame({
                    'Date': stats['dates'][:len(stats['scores'])],
                    'Score': stats['scores']
                })
                fig = px.line(trend_df, x='Date', y='Score', markers=True,
                             title='Score History')
                st.plotly_chart(fig, use_container_width=True)
            
            # Hole-by-hole analysis
            st.subheader("Hole-by-Hole Analysis")
            
            holes_data = stats['holes_data']
            hole_df_data = []
            
            for hole_num in sorted(holes_data.keys()):
                data = holes_data[hole_num]
                if data['scores']:
                    par = data['pars'][0] if data['pars'] else 0
                    avg = sum(data['scores']) / len(data['scores'])
                    hole_df_data.append({
                        'Hole': hole_num,
                        'Par': par,
                        'Avg Score': f"{avg:.2f}",
                        'vs Par': f"{avg - par:+.2f}",
                        'Best': min(data['scores']),
                        'Worst': max(data['scores']),
                        'Eagles': data['eagles'],
                        'Birdies': data['birdies'],
                        'Pars': data['pars_count'],
                        'Bogeys': data['bogeys'],
                        'Dbl+': data['double_bogeys'] + data['worse']
                    })
            
            hole_df = pd.DataFrame(hole_df_data)
            st.dataframe(hole_df, use_container_width=True)
            
            # Birdie holes highlight
            st.subheader("🎯 Birdie Opportunities")
            birdie_holes = hole_df[hole_df['Birdies'] > 0].sort_values('Birdies', ascending=False)
            
            if len(birdie_holes) > 0:
                st.write("Holes where you've made birdies:")
                st.dataframe(birdie_holes[['Hole', 'Par', 'Birdies', 'Avg Score']], 
                           use_container_width=True)
            else:
                st.info("No birdies yet on this course. Keep trying!")

# Hole Analysis Page
elif page == "🎯 Hole Analysis":
    st.header("Specific Hole Analysis")
    
    courses = get_courses(rounds)
    selected_course = st.selectbox("Select a course", courses)
    
    hole_num = st.number_input("Select hole number", min_value=1, max_value=18, value=1)
    
    if selected_course and hole_num:
        hole_data = analyze_hole(rounds, selected_course, hole_num)
        
        if hole_data['scores']:
            par = hole_data['par']
            times_played = len(hole_data['scores'])
            avg_score = sum(hole_data['scores']) / times_played
            
            # Summary metrics
            col1, col2, col3, col4 = st.columns(4)
            
            with col1:
                st.metric("Par", par)
            with col2:
                st.metric("Times Played", times_played)
            with col3:
                st.metric("Average Score", f"{avg_score:.2f}")
            with col4:
                st.metric("vs Par", f"{avg_score - par:+.2f}")
            
            st.markdown("---")
            
            # Score distribution
            st.subheader("Score Distribution")
            
            col1, col2, col3, col4, col5, col6 = st.columns(6)
            
            with col1:
                st.metric("Eagles", f"{hole_data['eagles']}")
                st.caption(f"{hole_data['eagles']/times_played*100:.1f}%")
            with col2:
                st.metric("Birdies", f"{hole_data['birdies']}")
                st.caption(f"{hole_data['birdies']/times_played*100:.1f}%")
            with col3:
                st.metric("Pars", f"{hole_data['pars']}")
                st.caption(f"{hole_data['pars']/times_played*100:.1f}%")
            with col4:
                st.metric("Bogeys", f"{hole_data['bogeys']}")
                st.caption(f"{hole_data['bogeys']/times_played*100:.1f}%")
            with col5:
                st.metric("Double", f"{hole_data['double_bogeys']}")
                st.caption(f"{hole_data['double_bogeys']/times_played*100:.1f}%")
            with col6:
                st.metric("Triple+", f"{hole_data['worse']}")
                st.caption(f"{hole_data['worse']/times_played*100:.1f}%")
            
            # Chart
            score_dist = {
                'Eagles': hole_data['eagles'],
                'Birdies': hole_data['birdies'],
                'Pars': hole_data['pars'],
                'Bogeys': hole_data['bogeys'],
                'Double': hole_data['double_bogeys'],
                'Triple+': hole_data['worse']
            }
            
            fig = go.Figure(data=[go.Bar(
                x=list(score_dist.keys()),
                y=list(score_dist.values()),
                marker_color=['gold', 'lightgreen', 'lightblue', 'orange', 'red', 'darkred']
            )])
            fig.update_layout(title=f"Score Distribution - Hole {hole_num}")
            st.plotly_chart(fig, use_container_width=True)
            
            # Recent history
            st.subheader("Recent History")
            history_data = []
            
            for i, (date, score) in enumerate(zip(hole_data['dates'][:10], hole_data['scores'][:10])):
                diff = score - par
                if diff <= -2:
                    result = f"Eagle ({diff:+d})"
                elif diff == -1:
                    result = f"Birdie ({diff:+d})"
                elif diff == 0:
                    result = "Par"
                elif diff == 1:
                    result = f"Bogey ({diff:+d})"
                elif diff == 2:
                    result = f"Double ({diff:+d})"
                else:
                    result = f"Triple+ ({diff:+d})"
                
                history_data.append({'Date': date, 'Score': score, 'Result': result})
            
            st.dataframe(pd.DataFrame(history_data), use_container_width=True)
            
            # Insights
            st.subheader("💡 Insights")
            
            under_par = hole_data['eagles'] + hole_data['birdies']
            under_pct = under_par / times_played * 100
            
            if under_pct > 20:
                st.success(f"✓ Strong hole! You score under par {under_pct:.1f}% of the time.")
            elif under_pct > 10:
                st.info(f"✓ Good birdie opportunity - {under_pct:.1f}% under par rate.")
            
            if avg_score - par >= 1.5:
                st.warning(f"⚠ This hole is costing you {avg_score - par:.2f} strokes per round.")
            elif avg_score - par <= -0.3:
                st.success(f"✓ You're gaining {par - avg_score:.2f} strokes per round on this hole!")
        else:
            st.info("No data available for this hole.")

# Trends Page
elif page == "📈 Trends":
    st.header("Performance Trends")
    
    # Overall score trend
    st.subheader("Overall Score Trend")
    
    all_scores = []
    all_dates = []
    
    for r in rounds:
        if r.get('total_score') and r.get('date'):
            all_scores.append(r['total_score'])
            all_dates.append(r['date'])
    
    if all_scores:
        trend_df = pd.DataFrame({
            'Date': all_dates,
            'Score': all_scores
        })
        
        fig = px.scatter(trend_df, x='Date', y='Score', 
                        trendline="lowess",
                        title='All Rounds - Score Trend')
        st.plotly_chart(fig, use_container_width=True)
    
    # Scoring distribution
    st.subheader("Scoring Distribution")
    
    all_stats = defaultdict(int)
    for r in rounds:
        stats = r.get('stats', {})
        for key, value in stats.items():
            all_stats[key] += value
    
    fig = go.Figure(data=[go.Bar(
        x=['Eagles', 'Birdies', 'Pars', 'Bogeys', 'Double', 'Triple+'],
        y=[all_stats['eagles'], all_stats['birdies'], all_stats['pars'],
           all_stats['bogeys'], all_stats['double_bogeys'], all_stats['worse']],
        marker_color=['gold', 'lightgreen', 'lightblue', 'orange', 'red', 'darkred']
    )])
    fig.update_layout(title='Overall Scoring Distribution')
    st.plotly_chart(fig, use_container_width=True)

# Footer
st.markdown("---")
st.caption("Golf Performance Analyzer | Powered by Streamlit")
